### PR TITLE
Make the website entirely static and almost JavaScript free

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
This PR:

- Make the website entirely static (We don't use the fact that it's a building framework, and we don't even maintain it properly, there's 0 reason not to move to something static)
- ~~Remove every single piece of JavaScript (this mean that this removes: the theme switcher and the search box)~~ **Edit:** At the request of @unixfox we're keeping the JS used for the theme switcher
- ~~Make the website dark~~ **Edit:** See previous point
- Remove the fonts
- Move all the resources (images, CSS) to proper folders
- Remove everything used to build it
- Update the dockerfile accordingly
- Clean the HTML

The website looks absolutely the same (other than the JS features, and the fonts that were removed) while simplifying thing a TON.

**Screenshots:** (Note: the GitHub icon at the top right doesn't work in my browser for whatever reason, but it's still here)

Homepage:
homepage

Donate page:
donate

### CODE REVIEW

**Comment by unixfox** [comment]
IMO the website looks better in white than in dark.

**Comment by TheFrenchGhosty** [comment]
@unixfox This is an 1 word change, this is true that the dark theme isn't great, so why not, sure.

**Comment by unixfox** [comment]
Can we keep the JS functions just for switching between dark and white? I think the theme should be white by default.

**Comment by TheFrenchGhosty** [comment]
@unixfox I don't know from which JS it's from, I'll take a look, but sure.

**Comment by TheFrenchGhosty** [comment]
@unixfox Done

**Review by SamantazFox — APPROVED** [review]
LGTM

**Comment by TheFrenchGhosty** [comment]
@SamantazFox So you agree in us dropping the building framework, correct?

**Comment by SamantazFox** [comment]
I mean, yeah? Not like we'll use it often, and we can still go back in git history if we need it again...

**Pull request merged**
